Section "InputClass"
    Identifier "Mouse"
    MatchIsPointer "on"
    Driver "libinput"

    Option "AccelProfile" "adaptive"
    Option "AccelSpeed" "-0.55"
    Option "NaturalScrolling" "false"
    Option "DisableWhileTyping" "false"
    Option "DragLockButtons" "0"
EndSection
