## name: Cherry Midnight
## author: nullxception
## license: GPLv3
## upstream: https://github.com/nullxception/cherry-kde/raw/main/kitty/cherry-midnight.conf

foreground #bdc3df
background #101020
selection_foreground #101017
selection_background #bdc3df

cursor #bdc3df
cursor_text_color #101017
url_color #85b6ff

tab_bar_background #101017
active_tab_foreground #bdc3df
active_tab_background #33333f
inactive_tab_foreground #dedeff
inactive_tab_background #101017

# Black
color0  #33333f
color8  #43435a

# Red
color1  #ff568e
color9  #ff69a2

# Green
color2  #64de83
color10 #73de8a

# Yellow
color3  #efff73
color11 #f3ff85

# Blue
color4  #73a9ff
color12 #65b2ff

# Magenta
color5  #946ff7
color13 #a481f7

# Cyan
color6  #6fddff
##62c6da
color14 #65b2ff
##71c2d9

# White
color7  #dedeff
color15 #ebebff
